#!/usr/bin/env bash
# codex-sync: generate the Codex CLI config surface from Claude-side state.
# One-way and idempotent. Everything it writes is a build artifact - never
# hand-edit the outputs.
#
# Outputs:
#   ~/.codex/AGENTS.md           <- <repo>/claude/instructions/shared/*.md
#                                   (same assembly as ~/.claude/AGENTS.md; Codex
#                                   has no import syntax, so a full copy)
#                                   (+ company workspace CLAUDE.md appended as a
#                                   scoped section when it exists)
#   ~/.codex/skills/<name>/      <- migrated copies of ~/.claude/skills/*/ and
#                                   skills/ shipped inside installed Claude
#                                   plugins (installed_plugins.json)
#   ~/.codex/codex-sync-manifest.json <- skill entries this script owns
#
# Migration rules per skill:
#   - copy the whole directory (rsync -a --delete), never symlink
#   - rewrite SKILL.md frontmatter: keep only `name` and `description`, and
#     force `name` to the destination dir name (Codex rejects unknown
#     frontmatter keys and reads the skill name from frontmatter)
#   - bodies are copied verbatim: no Claude->Codex text substitution, because
#     skills like g-cleanup legitimately reference ~/.claude paths
#
# Ownership: only entries recorded in the manifest are ever deleted.
# Codex-owned content (skills/.system/, unmanaged entries) is never touched.
# MCP servers and ~/.codex/config.toml are out of scope here: the company
# repo (toolbox/ai-configuration/codex/) merges those managed keys via its sync.sh,
# which also chains this script to keep AGENTS.md fresh.
#
# Usage: codex-sync.sh [--dry-run]

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$REPO_DIR/claude"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
SKILLS_DEST="$CODEX_HOME/skills"   # codex auto-discovery dir (verified in 0.143.0)
AGENTS_OUT="$CODEX_HOME/AGENTS.md"
MANIFEST="$CODEX_HOME/codex-sync-manifest.json"
CLAUDE_SKILLS="$HOME/.claude/skills"
PLUGINS_JSON="$HOME/.claude/plugins/installed_plugins.json"
COMPANY_WS_MD="$HOME/Documents/GitHubWork/CLAUDE.md"

# Every global skill with a SKILL.md is migrated to Codex.
EXCLUDE_SKILLS=()

# Claude plugins whose bundled skills stay out of Codex. Their descriptions all
# load into the Codex skills context budget, and Codex truncates descriptions
# once the budget is exceeded. Listed plugins remain fully available in Claude
# Code; only the Codex mirror is skipped.
EXCLUDE_PLUGINS=(example-skills figma)

AGENTS_MAX=32768   # codex project_doc_max_bytes default; combined cap with project docs
AGENTS_WARN=24576  # 75% of max: keep headroom for per-repo AGENTS.md

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

log()  { printf '%s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }
run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "[dry-run] $*"
  else
    "$@"
  fi
}

# Guards
if [[ -z "${HOME:-}" || "$CODEX_HOME" != "$HOME/"* ]]; then
  echo "ABORT: unexpected CODEX_HOME '$CODEX_HOME'" >&2
  exit 1
fi
if [[ ! -d "$SRC/instructions/shared" ]]; then
  echo "ABORT: source '$SRC/instructions/shared' not found" >&2
  exit 1
fi
for cmd in jq python3 rsync; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "ABORT: $cmd not found" >&2; exit 1; }
done

run mkdir -p "$CODEX_HOME" "$SKILLS_DEST"

# --- 1. AGENTS.md -----------------------------------------------------------
generate_agents_md() {
  cat <<'EOF'
# Codex CLI Instructions
# Auto-generated by grimoire/codex-sync.sh from claude/instructions/shared/ - DO NOT EDIT DIRECTLY
# Edit in ~/Documents/GitHubPrivate/grimoire and commit; sync regenerates this file.
EOF
  printf '\n'
  local f
  for f in "$SRC/instructions/shared/"*.md; do
    [[ -f "$f" ]] || continue
    cat "$f"
    printf '\n'
  done
  if [[ -f "$COMPANY_WS_MD" ]]; then
    printf '# Company Workspace Rules\n\n'
    printf 'This section applies ONLY when working under `~/Documents/GitHubWork/`.\n\n'
    cat "$COMPANY_WS_MD"
    printf '\n'
  fi
}

agents_size="$(generate_agents_md | wc -c | tr -d ' ')"
if (( agents_size > AGENTS_MAX )); then
  echo "ABORT: AGENTS.md would be ${agents_size} bytes > codex cap ${AGENTS_MAX} (project_doc_max_bytes). Trim claude/instructions/shared/." >&2
  exit 1
fi
if (( agents_size > AGENTS_WARN )); then
  warn "AGENTS.md is ${agents_size} bytes > ${AGENTS_WARN} (75% of the ${AGENTS_MAX} combined cap)"
fi
if [[ "$DRY_RUN" -eq 1 ]]; then
  log "[dry-run] generate $AGENTS_OUT (${agents_size} bytes)"
else
  tmp_agents="$(mktemp)"
  generate_agents_md > "$tmp_agents"
  mv "$tmp_agents" "$AGENTS_OUT"
  log "generated AGENTS.md (${agents_size} bytes)"
fi

# --- 2. Skills --------------------------------------------------------------
# Rewrite SKILL.md frontmatter in place: keep only name/description, force name.
strip_frontmatter() { # $1 = SKILL.md path, $2 = enforced skill name
  python3 - "$1" "$2" <<'PY'
import re, sys
path, name = sys.argv[1], sys.argv[2]
text = open(path, encoding="utf-8").read()
m = re.match(r"^---\n(.*?\n)---\n", text, re.S)
if not m:
    sys.exit("no frontmatter in " + path)
kept, keep = [], False
for line in m.group(1).splitlines():
    if re.match(r"^[A-Za-z0-9_-]+\s*:", line):
        key = line.split(":", 1)[0].strip()
        if key == "name":
            keep = False
            continue  # re-emitted below with the enforced name
        keep = key == "description"
    if keep:
        kept.append(line)
kept.insert(0, "name: " + name)
open(path, "w", encoding="utf-8").write(
    "---\n" + "\n".join(kept) + "\n---\n" + text[m.end():]
)
PY
}

is_excluded() {
  local name="$1" e
  for e in "${EXCLUDE_SKILLS[@]}"; do
    [[ "$name" == "$e" ]] && return 0
  done
  return 1
}

is_excluded_plugin() {
  local plugin="$1" e
  for e in "${EXCLUDE_PLUGINS[@]}"; do
    [[ "$plugin" == "$e" ]] && return 0
  done
  return 1
}

MIGRATED=()
migrate_skill() { # $1 = source dir, $2 = destination name
  local src="${1%/}" name="$2"
  # separate declaration: a same-command `local x=$name` would expand the
  # stale global `name`, not this call's argument
  local dest="$SKILLS_DEST/$name"
  if [[ ! -f "$src/SKILL.md" ]]; then
    warn "skip $name: no SKILL.md in $src"
    return
  fi
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "[dry-run] migrate skill: $name <- $src"
  else
    if [[ -L "$dest" ]]; then
      warn "replacing symlink at managed path: $dest"
      rm "$dest"
    fi
    rsync -a --delete "$src/" "$dest/"
    strip_frontmatter "$dest/SKILL.md" "$name"
    log "migrated skill: $name"
  fi
  MIGRATED+=("$name")
}

# a) global Claude skills
if [[ -d "$CLAUDE_SKILLS" ]]; then
  for d in "$CLAUDE_SKILLS"/*/; do
    [[ -d "$d" ]] || continue
    name="$(basename "$d")"
    if is_excluded "$name"; then
      log "skip (excluded): $name"
      continue
    fi
    migrate_skill "$d" "$name"
  done
fi

# b) skills shipped inside installed Claude plugins -> mp-<plugin>-<skill>
if [[ -f "$PLUGINS_JSON" ]]; then
  while IFS=$'\t' read -r plugin install_path; do
    [[ -n "$install_path" && -d "$install_path/skills" ]] || continue
    if is_excluded_plugin "$plugin"; then
      log "skip (excluded plugin): $plugin"
      continue
    fi
    for d in "$install_path/skills"/*/; do
      [[ -d "$d" ]] || continue
      migrate_skill "$d" "mp-${plugin}-$(basename "$d")"
    done
  done < <(jq -r '.plugins | to_entries[] | [(.key | split("@")[0]), (.value[0].installPath // empty)] | @tsv' "$PLUGINS_JSON")
fi

# --- 3. Orphan cleanup (manifest-scoped only) --------------------------------
if [[ -f "$MANIFEST" ]]; then
  while IFS= read -r old; do
    [[ -n "$old" && "$old" != ".system" ]] || continue
    still_owned=0
    for m in "${MIGRATED[@]:-}"; do
      [[ "$m" == "$old" ]] && still_owned=1
    done
    if [[ "$still_owned" -eq 0 && -e "$SKILLS_DEST/$old" ]]; then
      log "removing orphan skill: $old"
      run rm -rf "${SKILLS_DEST:?}/${old:?}"
    fi
  done < <(jq -r '.skills[]?' "$MANIFEST")
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  log "[dry-run] write manifest ($MANIFEST): ${MIGRATED[*]:-<empty>}"
  log "codex-sync dry-run complete (nothing written)"
else
  if [[ "${#MIGRATED[@]}" -eq 0 ]]; then
    printf '{"skills": []}\n' > "$MANIFEST"
  else
    printf '%s\n' "${MIGRATED[@]}" | jq -R . | jq -s '{skills: .}' > "$MANIFEST"
  fi
  log "codex-sync complete: ${#MIGRATED[@]} skill(s), AGENTS.md ${agents_size} bytes"
fi
