#!/usr/bin/env bash
# codex-sync: generate the Codex CLI config surface from Claude-side state.
# One-way and idempotent. Everything it writes is a build artifact - never
# hand-edit the outputs.
#
# Outputs:
#   ~/.codex/AGENTS.md           <- <repo>/claude/instructions/shared/*.md
#                                   (same assembly as ~/.claude/AGENTS.md; Codex
#                                   has no import syntax, so a full copy)
#   ~/.codex/hooks.json          <- <repo>/claude/settings.hooks.json groups merged
#                                   in (owned = every command runs $HOME/.claude/hooks/)
#                                   + Codex-only SessionStart workspace-context hook
#   ~/.codex/skills/<name>/      <- migrated copies of ~/.claude/skills/*/ and
#                                   skills/ shipped inside installed Claude
#                                   plugins (installed_plugins.json)
#   ~/.codex/codex-sync-manifest.json <- skill entries this script owns
#
# Migration rules per skill:
#   - copy the whole directory (rsync -a --delete), never symlink
#   - rewrite SKILL.md frontmatter: keep only `name` and `description`, and
#     force `name` to the destination dir name (Codex rejects unknown
#     frontmatter keys and reads the skill name from frontmatter)
#   - bodies are copied verbatim: no Claude->Codex text substitution, because
#     skills like g-cleanup legitimately reference ~/.claude paths
#
# Ownership: skills - only entries recorded in the manifest are ever deleted,
# Codex-owned content (skills/.system/, unmanaged entries) is never touched;
# hooks.json - only groups whose every command runs $HOME/.claude/hooks/.
# MCP servers and ~/.codex/config.toml are out of scope here: the company
# repo (toolbox/ai-configuration/codex/) merges those managed keys via its sync.sh,
# which also chains this script to keep AGENTS.md fresh.
#
# Usage: codex-sync.sh [--dry-run]

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$REPO_DIR/claude"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
SKILLS_DEST="$CODEX_HOME/skills"   # codex auto-discovery dir (verified in 0.143.0)
AGENTS_OUT="$CODEX_HOME/AGENTS.md"
MANIFEST="$CODEX_HOME/codex-sync-manifest.json"
CLAUDE_SKILLS="$HOME/.claude/skills"
PLUGINS_JSON="$HOME/.claude/plugins/installed_plugins.json"
COMPANY_WS='$HOME/Documents/GitHubWork'   # literal: expanded by the hook shell
HOOKS_SRC="$SRC/settings.hooks.json"
HOOKS_OUT="$CODEX_HOME/hooks.json"
# Claude-only handlers, never mirrored: codex login (pointless inside Codex),
# ko-term-check (parses the Claude transcript layout), delegation reminder
# (its rule lives in claude-only.md, which Codex never loads).
HOOK_EXCLUDE='codex login|ko-term-check\.sh|delegation-report-reminder\.sh'

# Every global skill with a SKILL.md is migrated to Codex.
EXCLUDE_SKILLS=()

# Claude plugins whose bundled skills stay out of Codex. Their descriptions all
# load into the Codex skills context budget, and Codex truncates descriptions
# once the budget is exceeded. Listed plugins remain fully available in Claude
# Code; only the Codex mirror is skipped.
EXCLUDE_PLUGINS=(example-skills figma)

# Codex applies no size limit to the global AGENTS.md (project_doc_max_bytes
# counts project docs only), so this is a self-imposed prompt-cost budget.
AGENTS_WARN=24576

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

log()  { printf '%s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }
run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "[dry-run] $*"
  else
    "$@"
  fi
}

# Guards
if [[ -z "${HOME:-}" || "$CODEX_HOME" != "$HOME/"* ]]; then
  echo "ABORT: unexpected CODEX_HOME '$CODEX_HOME'" >&2
  exit 1
fi
if [[ ! -d "$SRC/instructions/shared" ]]; then
  echo "ABORT: source '$SRC/instructions/shared' not found" >&2
  exit 1
fi
for cmd in jq python3 rsync; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "ABORT: $cmd not found" >&2; exit 1; }
done

run mkdir -p "$CODEX_HOME" "$SKILLS_DEST"

# --- 1. AGENTS.md -----------------------------------------------------------
generate_agents_md() {
  cat <<'EOF'
# Codex CLI Instructions
# Auto-generated by grimoire/codex-sync.sh from claude/instructions/shared/ - DO NOT EDIT DIRECTLY
# Edit in ~/Documents/GitHubPrivate/grimoire and commit; sync regenerates this file.
EOF
  printf '\n'
  local f
  for f in "$SRC/instructions/shared/"*.md; do
    [[ -f "$f" ]] || continue
    cat "$f"
    printf '\n'
  done
}

agents_size="$(generate_agents_md | wc -c | tr -d ' ')"
if (( agents_size > AGENTS_WARN )); then
  warn "AGENTS.md is ${agents_size} bytes > budget ${AGENTS_WARN} (loaded into every Codex session). Trim claude/instructions/shared/."
fi
if [[ "$DRY_RUN" -eq 1 ]]; then
  log "[dry-run] generate $AGENTS_OUT (${agents_size} bytes)"
else
  tmp_agents="$(mktemp)"
  generate_agents_md > "$tmp_agents"
  mv "$tmp_agents" "$AGENTS_OUT"
  log "generated AGENTS.md (${agents_size} bytes)"
fi

# --- 1b. hooks.json ----------------------------------------------------------
# Ownership marker: a group is ours when every handler command runs a script
# under $HOME/.claude/hooks/. Everything else in the file is preserved as-is.
generate_hooks_json() {
  local existing='{}'
  # Empty or invalid file: start from scratch instead of aborting the sync.
  [[ -s "$HOOKS_OUT" ]] && existing="$(jq -c . "$HOOKS_OUT" 2>/dev/null || echo '{}')"
  jq -n --argjson claude "$(cat "$HOOKS_SRC")" --argjson existing "$existing" \
        --arg excl "$HOOK_EXCLUDE" --arg ws "$COMPANY_WS" '
    def ours: (.hooks // []) | length > 0 and all((.command // "") | test("/\\.claude/hooks/"));
    (($existing.hooks // {}) | with_entries(.value |= map(select(ours | not)))) as $kept
    | ($claude
        | with_entries(.value |= (map(.hooks |= map(select(.command | test($excl) | not)))
                                  | map(select(.hooks | length > 0))))) as $mine
    | ($mine + {SessionStart: (($mine.SessionStart // [])
        + [{hooks: [{type: "command",
                     command: ("\"$HOME/.claude/hooks/workspace-context.sh\" \"" + $ws + "\"")}]}])}) as $mine
    | {description: ($existing.description
                     // "Groups whose commands run $HOME/.claude/hooks/ are generated by grimoire/codex-sync.sh; other groups are untouched."),
       hooks: (reduce ($mine | to_entries[]) as $e ($kept; .[$e.key] = ((.[$e.key] // []) + $e.value)))}
    | .hooks |= with_entries(select(.value | length > 0))
  '
}

if [[ -f "$HOOKS_SRC" ]]; then
  new_hooks="$(generate_hooks_json)"
  if [[ -f "$HOOKS_OUT" ]] && [[ "$(jq -S . "$HOOKS_OUT")" == "$(printf '%s' "$new_hooks" | jq -S .)" ]]; then
    log "hooks.json unchanged"
  elif [[ "$DRY_RUN" -eq 1 ]]; then
    log "[dry-run] merge grimoire hook groups into $HOOKS_OUT"
  else
    tmp_hooks="$(mktemp)"
    printf '%s\n' "$new_hooks" > "$tmp_hooks"
    mv "$tmp_hooks" "$HOOKS_OUT"
    log "merged hook groups into hooks.json"
    warn "hooks.json changed: Codex loads untrusted hooks but never runs them - trust the grimoire groups once via /hooks inside Codex"
  fi
fi

# --- 2. Skills --------------------------------------------------------------
# Rewrite SKILL.md frontmatter in place: keep only name/description, force name.
strip_frontmatter() { # $1 = SKILL.md path, $2 = enforced skill name
  python3 - "$1" "$2" <<'PY'
import re, sys
path, name = sys.argv[1], sys.argv[2]
text = open(path, encoding="utf-8").read()
m = re.match(r"^---\n(.*?\n)---\n", text, re.S)
if not m:
    sys.exit("no frontmatter in " + path)
kept, keep = [], False
for line in m.group(1).splitlines():
    if re.match(r"^[A-Za-z0-9_-]+\s*:", line):
        key = line.split(":", 1)[0].strip()
        if key == "name":
            keep = False
            continue  # re-emitted below with the enforced name
        keep = key == "description"
    if keep:
        kept.append(line)
kept.insert(0, "name: " + name)
open(path, "w", encoding="utf-8").write(
    "---\n" + "\n".join(kept) + "\n---\n" + text[m.end():]
)
PY
}

is_excluded() {
  local name="$1" e
  for e in "${EXCLUDE_SKILLS[@]}"; do
    [[ "$name" == "$e" ]] && return 0
  done
  return 1
}

is_excluded_plugin() {
  local plugin="$1" e
  for e in "${EXCLUDE_PLUGINS[@]}"; do
    [[ "$plugin" == "$e" ]] && return 0
  done
  return 1
}

MIGRATED=()
migrate_skill() { # $1 = source dir, $2 = destination name
  local src="${1%/}" name="$2"
  # separate declaration: a same-command `local x=$name` would expand the
  # stale global `name`, not this call's argument
  local dest="$SKILLS_DEST/$name"
  if [[ ! -f "$src/SKILL.md" ]]; then
    warn "skip $name: no SKILL.md in $src"
    return
  fi
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "[dry-run] migrate skill: $name <- $src"
  else
    if [[ -L "$dest" ]]; then
      warn "replacing symlink at managed path: $dest"
      rm "$dest"
    fi
    rsync -a --delete "$src/" "$dest/"
    strip_frontmatter "$dest/SKILL.md" "$name"
    log "migrated skill: $name"
  fi
  MIGRATED+=("$name")
}

# a) global Claude skills
if [[ -d "$CLAUDE_SKILLS" ]]; then
  for d in "$CLAUDE_SKILLS"/*/; do
    [[ -d "$d" ]] || continue
    name="$(basename "$d")"
    if is_excluded "$name"; then
      log "skip (excluded): $name"
      continue
    fi
    migrate_skill "$d" "$name"
  done
fi

# b) skills shipped inside installed Claude plugins -> mp-<plugin>-<skill>
if [[ -f "$PLUGINS_JSON" ]]; then
  while IFS=$'\t' read -r plugin install_path; do
    [[ -n "$install_path" && -d "$install_path/skills" ]] || continue
    if is_excluded_plugin "$plugin"; then
      log "skip (excluded plugin): $plugin"
      continue
    fi
    for d in "$install_path/skills"/*/; do
      [[ -d "$d" ]] || continue
      migrate_skill "$d" "mp-${plugin}-$(basename "$d")"
    done
  done < <(jq -r '.plugins | to_entries[] | [(.key | split("@")[0]), (.value[0].installPath // empty)] | @tsv' "$PLUGINS_JSON")
fi

# --- 3. Orphan cleanup (manifest-scoped only) --------------------------------
if [[ -f "$MANIFEST" ]]; then
  while IFS= read -r old; do
    [[ -n "$old" && "$old" != ".system" ]] || continue
    still_owned=0
    for m in "${MIGRATED[@]:-}"; do
      [[ "$m" == "$old" ]] && still_owned=1
    done
    if [[ "$still_owned" -eq 0 && -e "$SKILLS_DEST/$old" ]]; then
      log "removing orphan skill: $old"
      run rm -rf "${SKILLS_DEST:?}/${old:?}"
    fi
  done < <(jq -r '.skills[]?' "$MANIFEST")
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  log "[dry-run] write manifest ($MANIFEST): ${MIGRATED[*]:-<empty>}"
  log "codex-sync dry-run complete (nothing written)"
else
  if [[ "${#MIGRATED[@]}" -eq 0 ]]; then
    printf '{"skills": []}\n' > "$MANIFEST"
  else
    printf '%s\n' "${MIGRATED[@]}" | jq -R . | jq -s '{skills: .}' > "$MANIFEST"
  fi
  log "codex-sync complete: ${#MIGRATED[@]} skill(s), AGENTS.md ${agents_size} bytes"
fi
